services:
  hiddify:
    #only for local build and development
    #build: .

    #latest release version
    image: ghcr.io/hiddify/hiddify-manager@sha256:cca40161b44fb103febcbf7db4a5e5087e8ed756f9a05754f598737eb26b4ad6

    #latest beta version
    #image: ghcr.io/hiddify/hiddify-manager:beta

    #latest build of current development
    #image: ghcr.io/hiddify/hiddify-manager:dev

    #specific version
    #image: ghcr.io/hiddify/hiddify-manager:v10.80.0
    ports:
      - 443:443
      - 80:80
      - "11000-60000"  #for custom protocols like hysteria tuic wiregaurd 
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
       - ./docker-data/:/hiddify-data/
    environment:
      REDIS_URI_MAIN: 'redis://:REDIS_STRONG_PASS@redis:6379/0'
      REDIS_URI_SSH: 'redis://:REDIS_STRONG_PASS@redis:6379/1'
      SQLALCHEMY_DATABASE_URI: 'mysql+mysqldb://hiddifypanel:MYSQL_STRONG_PASS@mariadb/hiddifypanel?charset=utf8mb4'
    depends_on: 
      - mariadb
      - redis
    
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1       # Root user password
      MYSQL_DATABASE: hiddifypanel             # Initial database name
      MYSQL_USER: hiddifypanel                     # Custom username
      MYSQL_PASSWORD: MYSQL_STRONG_PASS             # Custom user password
    volumes:
      - ./docker-data/mariadb_data:/var/lib/mysql          # Persistent storage for database files

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    command: ["redis-server", "--requirepass", "REDIS_STRONG_PASS"]
    volumes:
      - ./docker-data/redis_data:/data                # Persistent storage for Redis data
    